### ISSUE TITLE
Broken on new Twitter

### ISSUE THREAD

**Issue by DanaMW** [scambier/userscripts#2]
It seems it no longer works on new Twitter, at least for me.

**Comment by scambier** [comment]
The "new" Twitter? Could you go on https://twitter.com/Stranger_Things/status/1125833074225315840 and confirm that the button does not appear when hovering your mouse?

![image](https://user-images.githubusercontent.com/3216752/57325051-78fcf980-7109-11e9-909f-5481af85c11d.png)

And if it does, what happens when clicking on it.

Also, do you have other userscripts or addons that interact with Twitter?

**Comment by DanaMW** [comment]
I tested as you asked and under original Twitter it works and downloads. When I switch to the new Twitter design it does not show a button at all. No scripts or skins other than it on twitter at the time.
The selection for the new is at the bottom of the user menu.

![Screenshot_2019-05-07 Stranger Things ( Stranger_Things) Twitter](https://user-images.githubusercontent.com/12940577/57325789-bccb1100-70bf-11e9-8b83-4974d77a2b99.png)

**Comment by scambier** [comment]
Alright, I might be a bit out of the loop, but it seems that this new design has still not be rolled out for everyone. Until then 🤷‍♂️

![image](https://user-images.githubusercontent.com/3216752/57326775-87e5ab00-710d-11e9-8d0e-8456c4684e88.png)

**Comment by DanaMW** [comment]
Well now i feel special in the hell that is twitter. :) How about that poor guy up there that mentioned tweetdeck is that doable?

**Comment by scambier** [comment]
I'll take a look at it asap :)

I'm keeping this issue open until I'm able to fix it

**Comment by scambier** [comment]
Ok, Twitter really went out of their way to make things difficult. I sent an update that _mostly_ works with the new design, but the button is broken on "blockquotes" (tweets quoting another tweet embedding a video). The quoted tweet's id is not available in the DOM, so I'm kinda stuck for now...

**Comment by jake2townz** [comment]
Crossing my fingers and hoping this gets fixed as soon as possible, @scambier 
This script was a godsend

**Comment by scambier** [comment]
It turns out that some external services support quoted tweets! Finally closing this issue 🎉
