### ISSUE TITLE
Twitter Video Download Button didn't appear in Chrome with Tampermonkey

### ISSUE THREAD

**Issue by librix** [scambier/userscripts#5]
![image](https://user-images.githubusercontent.com/10742127/73813762-f29e5100-481b-11ea-9618-a9ea058c13d7.png)
https://twitter.com/Shadow135Simmi/status/1224788732055818242?s=20

**Comment by scambier** [comment]
Welp, for me it works on Brave (Chromium) with Tampermonkey, but not Violentmonkey... Could you tell me if it works for you with Violentmonkey?

**Comment by librix** [comment]
Thank you. I try to change usage,  and now it works on Chrome with Violentmonkey.

**Comment by scambier** [comment]
Alright then 👍🏻, I'll still have a look to understand why it works (or not) on an engine or another
