### ISSUE TITLE
Can't click the button

### ISSUE THREAD

**Issue by dtlnor** [scambier/userscripts#7]
when I hover on the gif, it shows the button. But nothing happen when click.

**Comment by roberChen** [comment]
I have the save problem, using firefox, ubuntu

**Comment by scambier** [comment]
@dtlnor what are your browser and userscripts engine?
@roberChen what is your userscripts engine?

**Comment by Backstree** [comment]
I have the same problem,using Chrome on Windows10

**Comment by scambier** [comment]
Should be fixed with commit 0bf3b855538ed5a28657a70447e2775b2905e9ea
